version: '3.7'
services:
  feeder:
    environment:
      KEYCLOAK_AUTH-SERVER-URL: https://keycloak.sekan.eu
      KEYCLOAK_SSL-REQUIRED: none
      INFO_APP_CONTACT: "lhotak@knav.cz"
  feederfe:
    build:
      args:
        REACT_APP_KEYCLOAK_URL: https://keycloak.sekan.eu
  keycloak:
    image: tianon/true
    command: /true
    restart: "no"
    deploy:
      replicas: 0
      resources:
        limits:
          memory: 10m
