export const KRAMERIUS_ENUMS = {
	allDoctypes: [
		'convolute',
		'periodical',
		'monographbundle',
		'monograph',
		'collection',
		'clippingsvolume',
		'map',
		'sheetmusic',
		'graphic',
		'archive',
		'soundrecording',
		'manuscript',
		'monographunit',
		'soundunit',
		'track',
		'periodicalvolume',
		'periodicalitem',
		'article',
		'internalpart',
		'supplement',
		'page',
	],
};
